[workspace]

[package]
name = "c2rust"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"

[lib]
name = "c2rust"
path = "lib/c2rust-lib.rs"
crate-type = ["lib", "staticlib"]

[dependencies]
libc = "0.2"
