[windows]
inner_gap = 4
outer_gap = 4
smart_gaps = false

[borders]
colour = "periwinkle_blue"
size = 0
focus_colour = "burnt_umber"

[[binding]]
keys = [ "alt", "enter" ]
operation = "term"

[[binding]]
keys = [ "alt", "shift", "q" ]
operation = "kill focus"

[[binding]]
name = "takes screenshot with current date"
keys = [ "alt", "shift", "s" ]
operation = "screenshot"

[commands]
term = "exec alacritty"
screenshot = "scrot -s '%Y-%m-%d_$wx$h.png` -e"

[colours]
periwinkle_blue = "sand"
burnt_umber = "dad" 
