[windows]
inner_gap = 4
outer_gap = 4
smart_gaps = false

[borders]
colour = "periwinkle_blue"
size = 0
focus_colour = "burnt_umber"

[[binding]]
keys = [ "alt", "enter" ]
operation = "term"

[[binding]]
keys = [ "alt", "shift", "q" ]
operation = "kill focus"

[[binding]]
keys = [ "alt", "shift", "s" ]
operation = "screenshot"

[[command]]
name = "term"
action = "exec alacritty"

[[command]]
name = "screenshot"
action = "scrot -s '%Y-%m-%d_$wx$h.png` -e"

[[colour]]
name = "periwinkle blue"
value = 0xCCCCFF

[[colour]]
name = "burnt umber"
value = 0x8a3324 
