[windows]
inner_gap = 4
outer_gap = 4
smart_gaps = false

[borders]
colour = "periwinkle_blue"
size = 0
focus_colour = "burnt_umber"

[[binding]]
key = "Return"
mods = [ "Super_L" ]
operation = "exec alacritty"

[[binding]]
key =  "Q"
mods = [ "Super_L", "Shift_L" ]
operation = "kill focus"

[[binding]]
key = "S"
mods = [ "Super_L", "Shift_L" ]
operation = "scrot -s '%Y-%m-%d_$wx$h.png` -e"

[[colour]]
name = "periwinkle blue"
value = 0xCCCCFF

[[colour]]
name = "burnt umber"
value = 0x8a3324 
