[windows]
inner_gap = 4
outer_gap = 4
smart_gaps = false

[borders]
colour = "periwinkle_blue"
size = 0
focus_colour = "burnt_umber"

[[binding]]
key = "Return"
mods = [ "Super" ]
action = "term"

# [[binding]]
# key =  "Q"
# mods = [ "Super", "Shift" ]
# action = "kill focus"
# 
# [[binding]]
# key = "S"
# mods = [ "Super", "shift" ]
# action = "exit"

[[colour]]
name = "periwinkle blue"
value = 0xCCCCFF

[[colour]]
name = "burnt umber"
value = 0x8a3324 
