[windows]
inner_gap = 4
outer_gap = 4
smart_gaps = false

[borders]
colour = "periwinkle_blue"
size = 0
focus_colour = "burnt_umber"

[[binding]]
key = "Return"
mods = [ "Super" ]
operation = "term"

[[binding]]
key =  "Q"
mods = [ "Super", "Shift" ]
operation = "kill focus"

[[binding]]
key = "S"
mods = [ "Super", "shift" ]
operation = "screenshot"

[[command]]
name = "term"
action = "exec alacritty"

[[command]]
name = "screenshot"
action = "scrot -s '%Y-%m-%d_$wx$h.png` -e"

[[colour]]
name = "periwinkle blue"
value = 0xCCCCFF

[[colour]]
name = "burnt umber"
value = 0x8a3324 
